### ISSUE TITLE
string.split failure

### ISSUE THREAD

**Issue by gajowi** [cmip6dr/dreqPy#20]
When I install dreq on python3 I get:
 
~> drq -m LUMIP --mcfg 259200,60,64800,40,20,5,100
Traceback (most recent call last):
  File "/home/wil240/.virtualenvs/dreq/bin/drq", line 11, in <module>
    sys.exit(main_entry())
  File "/home/wil240/.virtualenvs/dreq/lib/python3.6/site-packages/dreqPy/dreqCmdl.py", line 53, in main_entry
    x.run()
  File "/home/wil240/.virtualenvs/dreq/lib/python3.6/site-packages/dreqPy/scope.py", line 1803, in run
    ll = string.split( self.adict['mcfg'], ',' )
AttributeError: module 'string' has no attribute 'split'

**Comment by gajowi** [comment]
I looked into it further. I think it should be str.split instead of string.split for python3 – and I think that is also OK for python2.

**Comment by martinjuckes** [comment]
Thanks for raising this ... your diagnosis is correct.

There is an updated version at  http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/trunk  .. you can checkout with `svn co http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/trunk` and install with `python setup.py install` .. I'll put it on pypi later this week.
