### ISSUE TITLE
Option '--xfr' of drq seems broken

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/dreqPy#8]
It seems that a _realmFlt_ function is not defined

```
bash-4.1$ drq -m PMIP --xfr --xlsDir xls3 --xls
Writing xls3/requestVol_cm.pm_1_1.xlsx
Writing xls3/requestVol_CMIP_1_1.xlsx
Traceback (most recent call last):
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatm14/bin/drq", line 11, in <module>
    sys.exit(main_entry())
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatm14/lib/python2.7/site-packages/dreqPy/dreqCmdl.py", line 45, in main_entry
    x.run()
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatm14/lib/python2.7/site-packages/dreqPy/scope.py", line 1810, in run
    vs.analAll(pmax,mips=mips,html=False,makeTabs=makeXls)
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatm14/lib/python2.7/site-packages/dreqPy/volsum.py", line 121, in analAll
    self.anal(olab=olab,doUnique='TOTAL' in theseMips, makeTabs=makeTabs)
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatm14/lib/python2.7/site-packages/dreqPy/volsum.py", line 254, in anal
    table_utils.makeTab(self.sc.dq, subset=lex[e], dest=self.xlsDest('e',olab,el), collected=cc[e],byFreqRealm=self.tabByFreqRealm, tslice=tslice)
  File "/home/share/unix_files/cdat/miniconda2/envs/cdatm14/lib/python2.7/site-packages/dreqPy/table_utils.py", line 254, in __init__
    ixt['%s.%s' % (i.frequency,realmFlt( i.modeling_realm) )].append( i.uid )
NameError: global name 'realmFlt' is not defined
```

**Comment by martinjuckes** [comment]
Fixed in 01.00.13
